import ThemeProvider from "@/components/theme-provider";
import "@/styles/globals.css";
import ConvexClientProvider from "@/wrappers/ConvexClientComponent";
import type { Metadata } from "next";
import { Bebas_Neue, Oxygen, Ubuntu } from "next/font/google";

const oxygen = Oxygen({
  subsets: ["latin-ext"],
  display: "swap",
  weight: "400",
});

const bebasNeue = Bebas_Neue({
  subsets: ["latin-ext"],
  display: "swap",
  weight: "400",
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={oxygen.className}
        style={{
          scrollBehavior: "smooth",
        }}
      >
        <ThemeProvider attribute="class">
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
